apiVersion: v1
kind: Secret
metadata:
    name: flashcards-app-secret
    namespace: flashcards-app
type: Opaque
stringData:
    DATABASE_URL: 'postgresql://myuser:mypassword@postgres:5432/mydatabase'
    JWT_SECRET: ''
    JWT_EXPIRES_IN: '1800'
    JWT_REFRESH_SECRET: ''
    JWT_REFRESH_EXPIRES_IN: '604800'
    RABBITMQ_URL: 'amqp://guest:guest@rabbitmq:5672'
